# This is a basic workflow to help you get started with Actions

name: Deploy Storage Account (dev)

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v3.0.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy storage account to dev
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group create \
              --resource-group dev \
              --name storageaccount-dev \
              --template-file storageaccount.bicep \
              --parameters @storageaccount-dev.parameters.json
